name: build

on: [push]

jobs:
  py:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        architecture: 'x64'
    - name: install
      run: |
        make install
    - name: test
      run: |
        make test
    - name: check
      run: |
        make check
